# Generated by Django 5.0.7 on 2024-08-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFundones', '0003_alter_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('P', 'Personalizado')], max_length=1),
        ),
    ]
