# Generated by Django 5.0.7 on 2024-08-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFundones', '0004_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('', 'Gênero'), ('M', 'Masculino'), ('F', 'Feminino'), ('P', 'Personalizado')], max_length=1),
        ),
    ]
