# Generated by Django 5.0.7 on 2024-08-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFundones', '0006_alter_customuser_bday_alter_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bday',
            field=models.CharField(max_length=10),
        ),
    ]
