# Generated by Django 5.0.7 on 2024-08-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFundones', '0010_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
