# Generated by Django 5.0.7 on 2024-09-08 02:07

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFundones', '0011_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='description_bio',
            field=models.CharField(default=datetime.datetime.now, max_length=160),
            preserve_default=False,
        ),
    ]
