# Generated by Django 5.0.7 on 2024-09-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFundones', '0012_customuser_created_at_customuser_description_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description_bio',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
